quarkus:
  banner:
    enabled: false
  datasource:
    devservices:
      image-name: 'docker.io/library/postgres:16'
  hibernate-orm:
    database:
      generation: none
  http:
    non-application-root-path: /
  swagger-ui:
    always-include: true
    operations-sorter: method

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: osetrm Legal Entity API
          version: 0.0.1
          description: API for retrieving legal entities
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html